openssl_privatekey_info: move main code to module_utils to allow easier implementation of diff mode
ansible-collections/community.crypto pull request #205
Opened 2021-03-20 21:08 UTC by felixfontein

##### SUMMARY
Subset of #150.

##### ISSUE TYPE
- Refactoring Pull Request

##### COMPONENT NAME
openssl_privatekey_info

2021-05-14 17:41 UTC, Ajpantuso requested changes
No functional issues and the new exceptions raised in `get_info` match the previous "direct" calls to `fail_json`

2021-05-14 17:41 UTC, Ajpantuso commented on plugins/modules/openssl_privatekey_info.py
> +        except Exception as e:
```suggestion
        except (IOError, OSError) as e:
```

2021-05-14 17:41 UTC, Ajpantuso commented on plugins/module_utils/crypto/module_backends/privatekey_info.py
> +        raise Exception('Unsupported value for backend: {0}'.format(backend))
```suggestion
        raise ValueError('Unsupported value for backend: {0}'.format(backend))
```

2021-05-14 21:50 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-05-15 06:24 UTC, merged

2021-05-15 06:24 UTC, felixfontein commented
@Ajpantuso thanks again for reviewing this one as well! :)