x509_certificate_info: move main code to module_utils to allow easier implementation of diff mode
ansible-collections/community.crypto pull request #206
Opened 2021-03-20 21:08 UTC by felixfontein

##### SUMMARY
Subset of #150.

##### ISSUE TYPE
- Refactoring Pull Request

##### COMPONENT NAME
x509_certificate_info

2021-03-20 21:49 UTC, felixfontein commented
recheck

2021-05-15 18:48 UTC, Ajpantuso requested changes
Looks good with same explicit exception suggestions as the previous reviews.

2021-05-15 18:48 UTC, Ajpantuso commented on plugins/module_utils/crypto/module_backends/certificate_info.py
> +            except AttributeError as dummy:
```suggestion
            except AttributeError:
```

2021-05-15 18:48 UTC, Ajpantuso commented on plugins/module_utils/crypto/module_backends/certificate_info.py
> +        raise Exception('Unsupported value for backend: {0}'.format(backend))
```suggestion
        raise ValueError('Unsupported value for backend: {0}'.format(backend))
```

2021-05-15 18:48 UTC, Ajpantuso commented on plugins/modules/x509_certificate_info.py
> +        except Exception as e:
```suggestion
        except (IOError, OSError) as e:
```

2021-05-15 20:35 UTC, Ajpantuso approved these changes
LGTM, thanks!

2021-05-15 20:48 UTC, merged

2021-05-15 20:52 UTC, felixfontein commented
@Ajpantuso thanks a lot for reviewing this! :)