Allow to specify subject (for CSRs) and issuer (for CRLs) ordered
ansible-collections/community.crypto pull request #316
Opened 2021-10-30 11:31 UTC by felixfontein

##### SUMMARY
Fixes #291.

##### ISSUE TYPE
- Bugfix Pull Request
- Feature Pull Request

##### COMPONENT NAME
acme_certificate
openssl_csr
openssl_csr_pipe
x509_crl

2021-10-30 12:27 UTC, felixfontein commented
ready_for_review

2021-10-31 13:19 UTC, Ajpantuso requested changes
A few minor comments, but otherwise looks good.

2021-10-31 13:19 UTC, Ajpantuso commented on changelogs/fragments/315-ordered-names.yml
> +  - "acme_certificate - the ``subject`` and ``issuer`` fields in in the ``select_chain`` entries are now stricter validated (https://github.com/ansible-collections/community.crypto/pull/316)."
```suggestion
  - "acme_certificate - the ``subject`` and ``issuer`` fields in in the ``select_chain`` entries are now more strictly validated (https://github.com/ansible-collections/community.crypto/pull/316)."
```

2021-10-31 13:19 UTC, Ajpantuso commented on plugins/module_utils/crypto/support.py
> +            raise ValueError('Value for {key} must be either a string or a list of strings'.format(key=key))
```suggestion
                raise TypeError(
                    'Value for {key} in {name} must be either a string or a list of strings'.format(key=key, name=name_field_name))
            raise TypeError('Value for {key} must be either a string or a list of strings'.format(key=key))
```

2021-10-31 13:19 UTC, Ajpantuso commented on plugins/module_utils/crypto/support.py
> +        except ValueError as exc:
```suggestion
        except (TypeError, ValueError) as exc:
```

2021-10-31 13:19 UTC, Ajpantuso commented on plugins/modules/x509_crl.py
> +        except ValueError as exc:
```suggestion
        except (TypeError, ValueError) as exc:
```

2021-10-31 13:23 UTC, felixfontein commented on plugins/module_utils/crypto/support.py
> +                    raise ValueError('Values for {key} must be strings'.format(key=key))
```suggestion
                        raise TypeError('Values for {key} in {name} must be strings'.format(key=key, name=name_field_name))
                    raise TypeError(Values for {key} must be strings'.format(key=key))
```

2021-10-31 13:31 UTC, felixfontein commented
@Ajpantuso what do you think of d497231e1cd2777ee7fe6bea856975d7b905101e and 196c85ffe25a171bd2b5f8fe27d38ea41eaf04bb? I think it's better to reject such values outright instead of silently ignoring them. The silent ignore makes sense for the explicit option fields for the CSR modules (or well, ignoring only `None` would make even more sense...), but I don't think it should happen for the other fields. What do you think?

2021-10-31 13:58 UTC, Ajpantuso commented
> @Ajpantuso what do you think of [d497231](https://github.com/ansible-collections/community.crypto/commit/d497231e1cd2777ee7fe6bea856975d7b905101e) and [196c85f](https://github.com/ansible-collections/community.crypto/commit/196c85ffe25a171bd2b5f8fe27d38ea41eaf04bb)? I think it's better to reject such values outright instead of silently ignoring them. The silent ignore makes sense for the explicit option fields for the CSR modules (or well, ignoring only `None` would make even more sense...), but I don't think it should happen for the other fields. What do you think?

Makes sense to me. Silently ignoring could even lead users to believe that defaults would be applied from say their OpenSSL config. More explicit is better in this case.

2021-10-31 14:02 UTC, Ajpantuso approved these changes
LGTM

2021-10-31 14:05 UTC, merged

2021-10-31 14:05 UTC, felixfontein commented
@Ajpantuso thanks again for reviewing this!